edit pipeline

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -29,9 +29,22 @@ jobs:
         with:
           service-account-token: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
           type-token: iam
-      - name: Test
-        run: echo ${{ steps.generation-iam-token.outputs.iam-token }}
-      # - name: Setup Terraform
-      #   uses: hashicorp/setup-terraform@v2
-      #   with:
-      #     terraform_version: ${{ secrets.TERRAFORM_VERSION }}
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: ${{ secrets.TERRAFORM_VERSION }}
+      - name: Terraform Init
+        id: init
+        env:
+          TF_VAR_yc_token: ${{ steps.generation-iam-token.outputs.iam-token }}
+          TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID}}
+          TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID}}
+        run: terraform init
+      - name: Terraform Format
+        id: fmt
+        run: terraform fmt -check
+      - name: Terraform Validate
+        id: validate
+        # Run even if formatting fails
+        if: success() || failure()
+        run: terraform validate -no-color
